<?php
/*
 * Copyright 2013 by Jerrick Hoang, Ivy Xing, Sam Roberts, James Cook,
 * Johnny Coster, Judy Yang, Jackson Moniaga, Oliver Radwan,
 * Maxwell Palmer, Nolan McNair, Taylor Talmage, and Allen Tucker.
 * This program is part of RMH Homebase, which is free software.  It comes with
 * absolutely no warranty. You can redistribute and/or modify it under the terms
 * of the GNU General Public License as published by the Free Software Foundation
 * (see <http://www.gnu.org/licenses/ for more information).
 *
 */
?>
<?php
/*
 * Created on Mar 28, 2008
 * @author Oliver Radwan <oradwan@bowdoin.edu>
 */
?>
<?PHP
session_cache_expire(30);
session_start();

$loggedIn = false;
    $accessLevel = 0;
    $userID = null;
    $isAdmin = false;
    if (!isset($_SESSION['access_level']) || $_SESSION['access_level'] < 1) {
        header('Location: login.php');
        die();
    }
    if (isset($_SESSION['_id'])) {
        $loggedIn = true;
        // 0 = not logged in, 1 = standard user, 2 = manager (Admin), 3 super admin (TBI)
        $accessLevel = $_SESSION['access_level'];
        $isAdmin = $accessLevel >= 2;
        $userID = $_SESSION['_id'];
    } else {
        header('Location: login.php');
        die();
    }
    if ($isAdmin && isset($_GET['id'])) {
        require_once('include/input-validation.php');
        $args = sanitize($_GET);
        $id = strtolower($args['id']);
    } else {
        $id = $userID;
    }

    // Prevent users from deleting their own profile
    if ($id == $userID) {
        header('Location: viewProfile.php');
        die();
    }

    require_once('database/dbPersons.php');
    if (isset($_GET['removePic'])) {
      if ($_GET['removePic'] === 'true') {
      }
    }

    $user = retrieve_person($id);
    $viewingOwnProfile = $id == $userID;

?>
<!-- page generated by the BowdoinRMH software package -->
<html>
    <head>     <link rel="icon" type="image/png" href="images/micah-favicon.png">

        <meta HTTP-EQUIV="REFRESH" content="2; url=index.php">

        <?php require('universal.inc') ?>
    </head>
    <body>
        <main>
                <div class="alert alert-success">This <?php echo $user->get_first_name() . ' ' . $user->get_last_name() ?> has been deleted.</div>
                <?php
                remove_person($user->get_id());
                ?>
        </main>
    </body>
</html>